version: '2'
services:
    nginx:
        hostname: ${APP_ENV}-nginx
        ports:
            - 80:80
        volumes:
            - ${API_DOCKERFILE_DIR}:${API_PROJECT_ROOT_PATH}
            - ${FRONT_DOCKERFILE_DIR}:/usr/src/app
            - ./nginx/config/${APP_ENV}-default.conf:/etc/nginx/conf.d/default.conf
        working_dir : /var/www
        restart: always

    database:
        image: mariadb:10.1
        hostname: ${APP_ENV}-database
        ports:
            - 33061:3306
        volumes:
            - ./database/volume:/var/lib
            - ./database/my.cnf:/etc/mysql/my.cnf
        working_dir : /data
        environment:
            - MYSQL_USER=master
            - MYSQL_PASSWORD=secret
            - MYSQL_DATABASE=sdw_service
            - MYSQL_ROOT_PASSWORD=secret
            - TZ=Asia/Seoul
        restart: always

    redis:
        image: redis
        hostname: ${APP_ENV}-redis
        restart: always
